// #### Base Database Schema ####
// 部門（基礎權限） 參考關聯用
Table PERMIFY_SERVICE_department_details {
  id bigint [pk, increment, note: "唯一識別碼"]
  code varchar(50) [unique, not null, note: "部門代碼"]
  name nvarchar(100) [not null, note: "部門名稱"]
  parent_id bigint [ref: > PERMIFY_SERVICE_department_details.id, null, note: "父部門ID"]
}

// 角色 （基礎權限）參考關聯用
Table PERMIFY_SERVICE_role_details {
  id bigint [pk, increment, note: "唯一識別碼"]
  department_id bigint [ref: > PERMIFY_SERVICE_department_details.id, not null, note: "部門ID"] 
  code varchar(50) [not null, note: "角色代碼"]
  name nvarchar(50) [not null, note: "角色名稱"]
  description nvarchar(300) [not null, note: "角色描述"]
}

// 用戶角色關聯（基礎權限）參考關聯用
Table PERMIFY_SERVICE_role_user {
  id bigint [pk, increment, note: "唯一識別碼"]
  role_id bigint [ref: > PERMIFY_SERVICE_role_details.id, not null, note: "角色ID"]
  user_id varchar(50) [not null, note: "用戶ID/帳號"]
  user_name nvarchar(100) [not null, note: "用戶姓名"]
  email varchar(100) [null, note: "用戶信箱"]
  
  created_date datetime2 [not null, default: `GETDATE()`, note: "建立時間"]
  created_by varchar(50) [not null, note: "建立人員"]
  updated_date datetime2 [not null, default: `GETDATE()`, note: "最後修改時間"]
  updated_by varchar(50) [not null, note: "最後修改人員"]
  
  // 複合唯一索引：一個用戶在一個角色中只能有一筆記錄
  indexes {
    (role_id, user_id) [unique, name: "UK_role_user"]
  }
}


// #### RBKCP Database Schema ####

// 2025-07-30 新增sequence
// 主館
Table domain {
  id int [pk, increment, note: "ID"]
  name nvarchar(50) [not null, note: "主館名稱"]
  description nvarchar(200) [null, note: "主館說明"]
  enable bit [not null, note: "啟用狀態: 0-停用, 1-啟用", default: 1]
  sequence int [not null, default: 0, note: "序號"]
  create_time datetime2 [not null, note: "建立時間"]
  creator varchar(20) [not null, note: "建立人員"]
  modify_time datetime2 [not null, note: "最後修改時間"]
  modifier varchar(20) [not null, note: "最後修改人員"]
  deleted bit [not null, default: 0, note: "軟刪除標記: 0-未刪除, 1-已刪除"]
  delete_time datetime2 [null, note: "刪除時間"]
  deleter varchar(20) [null, note: "刪除人員"]
}

// 2025-07-30 新增sequence
// 分館
Table subdomain {
  id int [pk, increment, note: "ID"]
  domain_id int [ref: > domain.id, not null, note: "主館ID"]
  name nvarchar(50) [not null, note: "分館名稱"]
  description nvarchar(200) [null, note: "分館說明"]
  enable bit [not null, note: "啟用狀態: 0-停用, 1-啟用", default: 1]
  sequence int [not null, default: 0, note: "序號"]
  
  create_time datetime2 [not null, note: "建立時間"]
  creator varchar(20) [not null, note: "建立人員"]
  modify_time datetime2 [not null, note: "最後修改時間"]
  modifier varchar(20) [not null, note: "最後修改人員"]
  deleted bit [not null, default: 0, note: "軟刪除標記: 0-未刪除, 1-已刪除"]
  delete_time datetime2 [null, note: "刪除時間"]
  deleter varchar(20) [null, note: "刪除人員"]
}

// 分館與部門關聯
Table subdomain_department_map {
  id bigint [pk, increment, note: "唯一識別碼"]
  department_id bigint [ref: > PERMIFY_SERVICE_department_details.id, null, note: "管理部門ID"]
  subdomain_id int [ref: > subdomain.id, not null, note: "分館ID"]

  create_time datetime2 [not null, note: "建立時間"]
  creator varchar(20) [not null, note: "建立人員"]
}

// 2025-07-30 新增sequence
// 文件分類
Table category {
  id bigint [pk, increment, note: "ID"]
  subdomain_id int [ref: > subdomain.id, not null, note: "分館ID"]
  parent_id bigint [ref: > category.id, null, note: "父分類ID"]
  name nvarchar(50) [not null, note: "分類名稱"]
  description nvarchar(200) [null, note: "分類說明"]
  enable bit [not null, note: "啟用狀態: 0-停用, 1-啟用", default: 1]
  enable_verify bit [not null, note: "是否啟用審核機制: 0-否, 1-是", default: 0]
  sequence int [not null, default: 0, note: "序號"]

  create_time datetime2 [not null, note: "建立時間"]
  creator varchar(20) [not null, note: "建立人員"]
  deleted bit [not null, default: 0, note: "軟刪除標記: 0-未刪除, 1-已刪除"]
  delete_time datetime2 [null, note: "刪除時間"]
  deleter varchar(20) [null, note: "刪除人員"]
}

// 2025-07-30 新增sequence
// 場景
Table scenario {
  id bigint [pk, increment, note: "唯一識別碼"]
  uuid char(36) [unique, not null, note: "全域唯一識別碼(UUID)"]
  name nvarchar(50) [not null, note: "場景名稱"]
  description nvarchar(200) [null, note: "場景描述"]
  embedding_model nvarchar(100) [not null, note: "嵌入模型"]
  vector_database nvarchar(100) [not null, note: "向量資料庫"]
  enable bit [not null, note: "啟用狀態: 0-停用, 1-啟用", default: 1]
  llm_agent_id varchar(100) [ null, note: "LLM代理ID"]
  threshold decimal(5,2) [null, note: "切片信心度閾值"]
  retrieval_empty_call_llm bit [not null, note: "檢索無結果時是否呼叫LLM: 0-停用, 1-啟用", default: 1]
  retrieval_empty_response nvarchar(1000) [null, note: "檢索無結果回應"]
  sequence int [not null, default: 0, note: "序號"]
  create_time datetime2 [not null, note: "建立時間"]
  creator varchar(20) [not null, note: "建立人員"]
  modify_time datetime2 [null, note: "最後修改時間"]
  modifier varchar(20) [null, note: "最後修改人員"]
  deleted bit [not null, default: 0, note: "軟刪除標記: 0-未刪除, 1-已刪除"]
  delete_time datetime2 [null, note: "刪除時間"]
  deleter varchar(20) [null, note: "刪除人員"]
}

// 場景與部門關聯
Table scenario_department_map {
  id bigint [pk, increment, note: "唯一識別碼"]
  department_id bigint [ref: > PERMIFY_SERVICE_department_details.id, null, note: "管理部門ID"]
  scenario_id bigint [ref: > scenario.id, not null, note: "場景ID"]

  create_time datetime2 [not null, note: "建立時間"]
  creator varchar(20) [not null, note: "建立人員"]
  Indexes {
    (scenario_id, department_id) [unique, name: "idx_scenario_department"]
  }
}

// 目前只有一個BGE_M3
// 場景所使用切片模型
Table scenario_chunk_model {
  id bigint [pk, increment, note: "唯一識別碼"]
  scenario_id bigint [ref: > scenario.id, not null, note: "場景ID"]
  model_name nvarchar(100) [not null, note: "模型名稱"]
  model_type nvarchar(50) [not null, note: "模型類型 (e.g., embedding, completion, chat)"]

  create_time datetime2 [not null, note: "建立時間"]
  creator varchar(20) [not null, note: "建立人員"]

  Indexes {
    (scenario_id, model_name) [unique, name: "idx_scenario_model_name"]
  }
}

// 附件
Table attachment {
  id bigint [pk, increment, note: "ID"]
  name nvarchar(100) [not null, note: "附件檔案名稱"]
  uuid char(36) [unique, not null, note: "全域唯一識別碼(UUID)"]
  extension nvarchar(10) [not null, note: "檔案類型"]
  storage_path nvarchar(200) [not null, note: "儲存路徑"]
  file_size decimal(18,2) [not null, note: "檔案大小"]

  create_time datetime2 [not null, note: "建立時間"]
  creator varchar(20) [not null, note: "建立人員"]
  deleted bit [not null, default: 0, note: "軟刪除標記: 0-未刪除, 1-已刪除"]
  delete_time datetime2 [null, note: "刪除時間"]
  deleter varchar(20) [null, note: "刪除人員"]
}

// 2025/06/17 current_version_id 移除 reference 約束，避免循環依賴
// 2025-07-30 新增sequence
// 知識庫 (系統參數控制知識庫版本需要審核)
Table knowledge_base {
  id bigint [pk, increment, note: "ID"]
  uuid char(36) [unique, not null, note: "全域唯一識別碼(UUID)"]
  scenario_id bigint [ref: > scenario.id, not null, note: "場景ID"]
  name nvarchar(50) [not null, note: "知識庫名稱"]
  description nvarchar(200) [null, note: "知識庫說明"]
  current_version_id bigint [null, note: "當前版本ID"]
  enable bit [not null, note: "啟用狀態: 0-停用, 1-啟用"]

  test_collection_name nvarchar(100) [ note: "MongoDB知識庫測試區集合名稱"]
  prod_collection_name nvarchar(100) [ note: "MongoDB知識庫正式區集合名稱"]

  lock_status tinyint [not null, default: 0, note: "鎖定狀態: 0-未鎖定, 1-手動鎖定, 2-自動鎖定(發布中)"]
  allow_manual_tag bit [not null, default: 1, note: "是否允許手動標籤: 0-不允許, 1-允許"]

  embedding_model nvarchar(100) [not null, note: "嵌入模型"]
  vector_database nvarchar(100) [not null, note: "向量資料庫"]
  sequence int [not null, default: 0, note: "序號"]
  create_time datetime2 [not null, note: "建立時間"]
  creator varchar(20) [not null, note: "建立人員"]
  modify_time datetime2 [not null, note: "最後修改時間"]
  modifier varchar(20) [not null, note: "最後修改人員"]
  deleted bit [not null, default: 0, note: "軟刪除標記: 0-未刪除, 1-已刪除"]
  delete_time datetime2 [null, note: "刪除時間"]
  deleter varchar(20) [null, note: "刪除人員"]
}

// 2025/06/27 新增collection_name
// 知識庫版本
Table knowledge_base_version {
  id bigint [pk, increment, note: "ID"]
  uuid char(36) [unique, not null, note: "全域唯一識別碼(UUID)"] 
  kb_id bigint [ref: > knowledge_base.id, not null, note: "知識庫ID"]
  version_number decimal(5,1) [not null, note: "版本號碼"]
  collection_name nvarchar(100) [not null, note: "MongoDB集合名稱"] 
  description nvarchar(200) [null, note: "版本描述"]
  publish_status tinyint [not null, note: "發布狀態: 0-未發布, 1-已發布, 2-歷史版本"]
  verify_status tinyint [not null, default: 0, note: "審核狀態: -1-審核退回,0-未送審, 1-審核中, 2-審核完成"]
  verify_user_id varchar(30) [null, note: "送審人員ID"]
  verify_time datetime2 [null, note: "送審時間"]
  create_time datetime2 [not null, note: "建立時間"]
  creator varchar(20) [not null, note: "建立人員"]
  modify_time datetime2 [not null, note: "最後修改時間"]
  modifier varchar(20) [not null, note: "最後修改人員"]
  deleted bit [not null, default: 0, note: "軟刪除標記: 0-未刪除, 1-已刪除"]
  delete_time datetime2 [null, note: "刪除時間"]
  deleter varchar(20) [null, note: "刪除人員"]

  Indexes {
    (kb_id, version_number) [unique, name: "idx_kb_version_unique"]
  }
}

// 知識庫上傳版本紀錄
Table knowledge_base_upload {
  id bigint [pk, increment, note: "唯一識別碼"]
  knowledge_base_id bigint [ref: > knowledge_base.id, not null, note: "知識庫ID"]
  upload_version_id bigint [null, note: "已上傳版本ID"]
  upload_start_time datetime2 [not null, note: "上傳開始時間"]
  upload_end_time datetime2 [note: "上傳結束時間"]
  received_time datetime2 [note: "更新完成時間"]
  create_time datetime2 [not null, note: "建立時間"]
}


// 知識庫與標籤庫關聯
Table knowledge_base_tag_library_map {
  id bigint [pk, increment, note: "唯一識別碼"]
  knowledge_base_id bigint [ref: > knowledge_base.id, not null, note: "知識庫ID"]
  tag_library_id bigint [ref: > tag_library.id, not null, note: "標籤庫ID"]

  create_time datetime2 [not null, note: "建立時間"]
  creator varchar(20) [not null, note: "建立人員"]
  Indexes {
    (knowledge_base_id, tag_library_id) [name: "idx_kb_tag"]
  }
}

// 2025/06/13. 標籤庫可能不會存在，僅標籤
// 標籤庫
Table tag_library {
  id bigint [pk, increment, note: "ID"]
  name nvarchar(20) [not null, note: "標籤庫名稱"]
  description nvarchar(100) [null, note: "標籤庫說明"]
  enable bit [not null, note: "啟用狀態: 0-停用, 1-啟用", default: 1]

  create_time datetime2 [not null, note: "建立時間"]
  creator varchar(20) [not null, note: "建立人員"] // Renamed from create_by
  modify_time datetime2 [not null, note: "最後修改時間"] // Renamed from last_update_time
  modifier varchar(20) [not null, note: "最後修改人員"] // Renamed from last_update_by
  deleted bit [not null, default: 0, note: "軟刪除標記: 0-未刪除, 1-已刪除"]
  delete_time datetime2 [null, note: "刪除時間"]
  deleter varchar(20) [null, note: "刪除人員"]
}

// 標籤
Table tag {
  id bigint [pk, increment, note: "ID"]
  tag_key nvarchar(20) [not null, note: "標籤鍵"]
  tag_value nvarchar(20) [not null, note: "標籤值"]
  source tinyint [not null, note: "來源: 1-其他, 2-標籤庫, 3-手動輸入"]
  enable bit [not null, note: "啟用狀態: 0-停用, 1-啟用", default: 1]

  create_time datetime2 [not null, note: "建立時間"]
  creator varchar(20) [not null, note: "建立人員"]
  deleted bit [not null, default: 0, note: "軟刪除標記: 0-未刪除, 1-已刪除"]
  delete_time datetime2 [null, note: "刪除時間"]
  deleter varchar(20) [null, note: "刪除人員"]
}

// 審核流程設定
Table verify_flow_template {
  id bigint [pk, increment, note: "唯一識別碼"]
  target_type tinyint [not null, note: "審核對象類型: 1-文件版本, 2-知識庫版本"]
  level tinyint [not null, default: 1, note: "審核關卡，1=第一關，2=第二關...，對應審核階段"]
  role_id bigint [ref: > PERMIFY_SERVICE_role_details.id, not null, note: "審核角色ID"]
  create_time datetime2 [not null, note: "建立時間"]
  creator varchar(20) [not null, note: "建立人員"]
}

// 審核流程紀錄
Table verify_flow_log {
  id bigint [pk, increment, note: "唯一識別碼"]
  target_type tinyint [not null, note: "審核對象類型: 1-文件版本, 2-知識庫版本"]
  target_version_id varchar(50) [not null, note: "對象版本ID (knowledge_base_version.id)"]
  verify_by nvarchar(30) [not null, note: "審核人員"]
  reason nvarchar(500) [null, note: "審核意見"]
  action tinyint [not null, note: "審核動作: 0-退回, 1-通過"]
  level tinyint [not null, default: 1, note: "審核關卡，1=第一關，2=第二關...，對應審核階段"]
  sequence int [not null, note: "審核順序，從1開始遞增"]
  create_time datetime2 [not null, note: "建立時間"]
}

//審核流程
Table verify_flow {
  id bigint [pk, increment, note: "唯一識別碼"]
  target_type tinyint [not null, note: "審核對象類型: 1-文件版本, 2-知識庫版本"]
  target_version_id varchar(50) [not null, note: "對象版本ID (document_version.id 或 knowledge_base_version.id)"]
  level tinyint [not null, note: "審核關卡，1=第一關，2=第二關..."]
  dept_role_id bigint [ref: > PERMIFY_SERVICE_department_role.id, not null, note: "審核角色ID"]
  action tinyint [not null, note: "審核動作: 0-退回, 1-通過"]
  action_time datetime2 [null, note: "動作時間"]
  status tinyint [not null, default: 0, note: "狀態: 0-未完成, 1-已完成"]
  create_time datetime2 [not null, note: "建立時間"]
  creator varchar(20) [not null, note: "建立人員"]
  modify_time datetime2 [not null, note: "最後修改時間"] 
  modifier varchar(20) [not null, note: "最後修改人員"]
  
  Indexes {
    (target_type, target_version_id, level, role_id) [unique, name: "idx_targetver_level_role"]
    (target_type, target_version_id, level) [name: "idx_targetver_level"]
  }
}